name: veggify_delivery_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.2.0
  provider: ^6.1.5+1
  fl_chart: ^0.66.0
  shared_preferences: ^2.5.3
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_places_flutter: ^2.1.1
  google_fonts: ^6.3.2
  latlong2: ^0.9.1
  flutter_map: ^8.2.2
  font_awesome_flutter: ^10.9.1
  audioplayers: ^6.5.1
  socket_io_client: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/splashimage.png
    - assets/otpimage.png
    - assets/registerimage.png
    - assets/home.png
    - assets/biriyani.png
    - assets/map.png
    - assets/chat.png
    - assets/scanner.png
    - assets/logo.png
    - assets/sounds/order_alert.mp3

# flutter_launcher_icons configuration MUST be top-level (not under `flutter:`)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/appstore.png"
  remove_alpha_ios: true
